# ADALINE implementation using tensorflow
intuition: https://sebastianraschka.com/Articles/2015_singlelayer_neurons.html

In [1]:
import tensorflow as tf
import time
from pprint import pprint

/home/anuj/.virtualenvs/video-analytics-2/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# heavy-side step function
def step(x):
    is_greater = tf.greater(x, 0)
    as_float = tf.to_float(is_greater)
    doubled = tf.multiply(as_float, 2)
    return tf.subtract(doubled, 1)

# linear activation function
def linear_activation(x, w):
    return tf.matmul(x, w)

def train_perceptron(X, y):
    # reason for dimension 3x1
    # 3 - since there are 2 inputs + 1 for bias
    # 1 - binary classification 
    # if there were 10 classes, it would have been 10 i.e., 3x10
    weights = tf.Variable(tf.random_normal([3, 1]))
    x_ = tf.placeholder(tf.float32, shape=[4,3], name = 'x-input')
    y_ = tf.placeholder(tf.float32, shape=[4,1], name = 'y-input')


    # going by perceptron learning rule
    # the heavy-side step function itself is the acativation here
    y_pred = linear_activation(X, weights)
    error = tf.subtract(y_, y_pred)
    mse = tf.reduce_mean(tf.square(error))

    train_step = tf.train.GradientDescentOptimizer(0.01).minimize(mse)

    init = tf.global_variables_initializer()
    sess = tf.Session()

    sess.run(init)

    t_start = time.clock()
    for i in range(1000):
        sess.run(train_step, feed_dict={x_: X, y_: y})
        if i % 100 == 0:
            print('Epoch: ' + str(i))
            print('weights: \n' + str(sess.run(weights, feed_dict={x_: X, y_: y})))
            print('cost: ' + str(sess.run(mse, feed_dict={x_: X, y_: y})))
            print('\n')
    t_end = time.clock()
    print('Elapsed time ', t_end - t_start)

    return sess, weights

### training input

In [3]:
T, F = 1.0, -1.0
bias = 1.0

# input
X = [
    [T, T, bias],
    [T, F, bias], 
    [F, T, bias],
    [F, T, bias]
]

# target/label
y = [
    [T],
    [F],
    [F],
    [F]
]

### training for AND gate

In [4]:
sess, weights = train_perceptron(X, y)

Epoch: 0
weights: 
[[-0.66724455]
 [-0.63413036]
 [-0.23864847]]
cost: 2.0611


Epoch: 100
weights: 
[[ 0.28055784]
 [ 0.07008365]
 [-0.40069702]]
cost: 0.5151828


Epoch: 200
weights: 
[[ 0.6260918 ]
 [ 0.48256007]
 [-0.64202464]]
cost: 0.156992


Epoch: 300
weights: 
[[ 0.79560083]
 [ 0.71243256]
 [-0.7977139 ]]
cost: 0.04844428


Epoch: 400
weights: 
[[ 0.8868609 ]
 [ 0.84019554]
 [-0.8871412 ]]
cost: 0.014959551


Epoch: 500
weights: 
[[ 0.93718666]
 [ 0.911195  ]
 [-0.93722385]]
cost: 0.0046197153


Epoch: 600
weights: 
[[ 0.9651017]
 [ 0.9506498]
 [-0.9651068]]
cost: 0.0014266459


Epoch: 700
weights: 
[[ 0.9806077]
 [ 0.9725756]
 [-0.9806083]]
cost: 0.00044056936


Epoch: 800
weights: 
[[ 0.9892236]
 [ 0.9847598]
 [-0.9892236]]
cost: 0.00013605625


Epoch: 900
weights: 
[[ 0.9940114]
 [ 0.9915307]
 [-0.9940114]]
cost: 4.201736e-05


('Elapsed time ', 1.363747)


### prediction

In [5]:
# predictions
X_test = [[T, T, bias], [T, F, bias]]

# expected ouput: 1, -1

In [6]:
predict = step(linear_activation(X_test, weights))
print('predictions: ', sess.run(predict))

('predictions: ', array([[ 1.],
       [-1.]], dtype=float32))
